insert into PUBLIC.GUESTS ( FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ( 'g1', 'g1', '997' );
insert into PUBLIC.GUESTS ( FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ( 'g2', 'g2', '998' );
insert into PUBLIC.GUESTS ( FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ( 'g3', 'g3', '999' );
insert into PUBLIC.GUESTS ( FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ( 'g4', 'g4', '112' );

insert into PUBLIC.ROOMS (ROOM_NUMBER) VALUES ( 'r1' );
insert into PUBLIC.ROOMS (ROOM_NUMBER) VALUES ( 'r2' );
insert into PUBLIC.ROOMS (ROOM_NUMBER) VALUES ( 'r3' );
insert into PUBLIC.ROOMS (ROOM_NUMBER) VALUES ( 'r4' );

insert into PUBLIC.BOOKINGS ( GUEST_ID, ROOM_ROOM_ID) VALUES ( 1, 1 );
insert into PUBLIC.BOOKINGS ( GUEST_ID, ROOM_ROOM_ID) VALUES ( 2, 2 );
insert into PUBLIC.BOOKINGS ( GUEST_ID, ROOM_ROOM_ID) VALUES ( 2, 3 );
insert into PUBLIC.BOOKINGS ( GUEST_ID, ROOM_ROOM_ID) VALUES ( 2, 4 );